export const GET_ALL_ACCOUNT_STATEMENT_REQUEST =
  "GET_ALL_ACCOUNT_STATEMENT_REQUEST";
export const GET_ALL_ACCOUNT_STATEMENT_SUCCESS =
  "GET_ALL_ACCOUNT_STATEMENT_SUCCESS";
export const GET_ALL_ACCOUNT_STATEMENT_FAIL = "GET_ALL_ACCOUNT_STATEMENT_FAIL";
export const GET_ALL_ACCOUNT_STATEMENT_RESET =
  "GET_ALL_ACCOUNT_STATEMENT_RESET";

export const GET_LIST_ACCOUNT_STATEMENT_REQUEST =
  "GET_LIST_ACCOUNT_STATEMENT_REQUEST";
export const GET_LIST_ACCOUNT_STATEMENT_SUCCESS =
  "GET_LIST_ACCOUNT_STATEMENT_SUCCESS";
export const GET_LIST_ACCOUNT_STATEMENT_FAIL =
  "GET_LIST_ACCOUNT_STATEMENT_FAIL";
export const GET_LIST_ACCOUNT_STATEMENT_RESET =
  "GET_LIST_ACCOUNT_STATEMENT_RESET";

export const GET_ACCOUNT_NAME_REQUEST = "GET_ACCOUNT_NAME_REQUEST";
export const GET_ACCOUNT_NAME_SUCCESS = "GET_ACCOUNT_NAME_SUCCESS";
export const GET_ACCOUNT_NAME_FAIL = "GET_ACCOUNT_NAME_FAIL";
export const GET_ACCOUNT_NAME_RESET = "GET_ACCOUNT_NAME_RESET";
