export const GET_ALL_OLD_QUESTIONS_REQUEST = "GET_ALL_OLD_QUESTIONS_REQUEST";
export const GET_ALL_OLD_QUESTIONS_SUCCESS = "GET_ALL_OLD_QUESTIONS_SUCCESS";
export const GET_ALL_OLD_QUESTIONS_FAIL = "GET_ALL_OLD_QUESTIONS_FAIL";
export const GET_ALL_OLD_QUESTIONS_RESET = "GET_ALL_OLD_QUESTIONS_RESET";
