export const GET_HEADER_CONTENT_REQUEST = "GET_HEADER_CONTENT_REQUEST";
export const GET_HEADER_CONTENT_SUCCESS = "GET_HEADER_CONTENT_SUCCESS";
export const GET_HEADER_CONTENT_FAIL = "GET_HEADER_CONTENT_FAIL";
export const GET_HEADER_CONTENT_RESET = "GET_HEADER_CONTENT_RESET";
