export const subject = [
  {
    id: 1,
    name: "Science",
    credit: "SCI (Credit: 4)",
    teacher: "Suresh Kumar Mandar",
    phone: "9841479789",
    imageUrl: "https://i.ibb.co/6mPDc4f/Science-Quotes.jpg",
  },
  {
    id: 2,
    name: "English",
    credit: "Eng (Credit: 4)",
    teacher: "Suresh Kumar Mandar",
    phone: "9841479789",
    imageUrl: "https://i.ibb.co/sypZmq4/english.jpg",
  },
  {
    id: 3,
    name: "Nepali",
    credit: "Nep (Credit: 4)",
    teacher: "Suresh Kumar Mandar",
    phone: "9841479789",
    imageUrl: "https://i.ibb.co/6mPDc4f/Science-Quotes.jpg",
  },
  {
    id: 4,
    name: "Socail Studies",
    credit: "SS (Credit: 4)",
    teacher: "Suresh Kumar Mandar",
    phone: "9841479789",
    imageUrl: "https://i.ibb.co/5s20zQR/ss.jpg",
  },
  {
    id: 5,
    name: "Math",
    credit: "Mth (Credit: 4)",
    teacher: "Suresh Kumar Mandar",
    phone: "9841479789",
    imageUrl: "https://i.ibb.co/6mPDc4f/Science-Quotes.jpg",
  },
  {
    id: 6,
    name: "General Knowledge",
    credit: "GK (Credit: 4)",
    teacher: "Suresh Kumar Mandar",
    phone: "9841479789",
    imageUrl: "https://i.ibb.co/Sw0XwNG/gk.jpg",
  },
  {
    id: 7,
    name: "Opt. Math",
    credit: "Opt (Credit: 4)",
    teacher: "Suresh Kumar Mandar",
    phone: "9841479789",
    imageUrl: "https://i.ibb.co/6mPDc4f/Science-Quotes.jpg",
  },
  {
    id: 8,
    name: "Computer science",
    credit: "C.SCI (Credit: 4)",
    teacher: "Suresh Kumar Mandar",
    phone: "9841479789",
    imageUrl: "https://i.ibb.co/ggPc7Lt/computer.jpg",
  },
];
